pipeline {
    agent any
    stages {
        stage('Unit Tests - Backend') {
            agent {

                docker {

                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }        
            steps {
                withEnv(["GOCACHE=${WORKSPACE}/.cache", "GOPATH=${WORKSPACE}/.go"]) {
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }
                }
            }
        }
    }
}
