pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'echo "Hello People who are learning Playqright"'
                sh 'date'
            }
        }
    }
}
